service: serverless-authorizer

frameworkVersion: ">=1.9.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: dev # Change it to environment variable
  region: us-east-1 #Change it
  memorySize: 512
  timeout: 10
  #deploymentBucket: com.serverless.photo.service.${self:provider.region}.deploys
  #deploymentBucket: com.serverless.photo.service.test009.deploys
  environment: # Service wide environment variables
    test: 1234
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

package:
  artifact: target/serverless-authorizer.jar

functions:
  authorizer:
    handler: com.test.serverless.authorizer.handler.AuthorizerHandler
    

