service: serverless-photo-service

frameworkVersion: ">=1.9.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: dev # Change it to environment variable
  region: us-east-1 #Change it
  memorySize: 512
  timeout: 10
  #deploymentBucket: com.serverless.photo.service.${self:provider.region}.deploys
  #deploymentBucket: com.serverless.photo.service.test009.deploys
  environment: # Service wide environment variables
    test: 1234
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

package:
  artifact: target/serverless-photo-service.jar

functions:
  getPhoto:
    handler: com.test.serverless.photo.service.handler.GetPhotoHandler
    events:
      - http:
          path: /api/v1/user/{userName}/photo
          method: get
          cors: true
  postPhoto:
    handler: com.test.serverless.photo.service.handler.PostPhotoHandler
    events:
      - http:
          path: /api/v1/user/{userName}/photo
          method: post
          cors: true
  imageCreated:
    handler: com.test.serverless.photo.service.handler.ImageCreatedHandler
    events:
      - s3:
          bucket: anilktalla-serverless-photo-service
          event: s3:ObjectCreated:*

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: anilktalla-serverless-photo-service-resized

